apps/base/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
]

apps/contacts/urls.py
from django.urls import path, include

from . import views

app_name = "contacts"

urlpatterns = [
    path("", views.ContactsListView.as_view(), name="show_all_contacts"),
    path("create_contact", views.ContactCreateView.as_view(), name="create_contact"),
    path("<int:pk>/", include([
        path('edit', views.ContactUpdateView.as_view(), name='edit'),
        path('delete', views.ContactDeleteView.as_view(), name='delete')
    ])),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('contacts/', include('apps.contacts.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.base.urls')),
]

apps/base/models.py
from django.db import models

# Create your models here.

apps/contacts/models.py
from django.core.validators import MaxLengthValidator
from django.db import models

from django.db.models import Field
from django.urls import reverse_lazy


class TagsChoices(models.TextChoices):
    FAMILY = 'family', '#family'
    FRIEND = 'friend', '#friend'
    WORK = 'work', '#work'


class SomeTag(models.Model):
    tag = models.CharField('Tag', help_text='Some tag for your contact', max_length=200)

    def __str__(self) -> str:
        return f'{self.tag}'

    __repr__ = __str__


class Contact(models.Model):
    contact_name = models.CharField('Contact Name',
                                    help_text='It is name of human',
                                    max_length=20,
                                    default='Vasya')
    phone_number = models.CharField('Phone Number',
                                    help_text='Phone number must start "380"',
                                    default='+380',
                                    max_length=20
                                    )

    birthday = models.CharField('Day of birth', max_length=20, default='01/01/99')

    tags = models.CharField(
        'Tags', max_length=100,
        help_text='Tags dor you Contact',
        choices=TagsChoices.choices,
        default=TagsChoices.WORK,
        blank=True,
    )

    tag_by_foreign_key = models.ForeignKey(
        SomeTag,
        related_name='tag_by_foreign_key',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    tag_by_many_to_many = models.ManyToManyField(
        SomeTag,
        related_name='tag_by_many_to_many',
    )

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.contact_name}'

    __repr__ = __str__

    def get_absolute_url(self):
        return reverse_lazy('contacts:edit', kwargs={'pk': self.pk})


class Tags(models.Model):
    tag = models.CharField('Tag',
                           max_length=50,
                           help_text='Tag for your contact')

    def __str__(self) -> str:
        return f'{self.tag}'

    __repr__ = __str__


class DetailForContact(models.Model):
    PHONE_NUMBER = 'Phone number'
    LINKEDIN = 'Linkedin'
    TELEGRAM = 'Telegram'
    EMAIL = 'Email'
    DETAIL_IN_CONTACT_CHOICES = [
        (PHONE_NUMBER, 'Phone number'),
        (LINKEDIN, 'Linkedin'),
        (TELEGRAM, 'Telegram'),
        (EMAIL, 'Email'),
    ]
    contact_type = models.CharField(
        'Details',
        max_length=100,
        help_text='Add details about you Contact',
        choices=DETAIL_IN_CONTACT_CHOICES,
        default=LINKEDIN,
        blank=True,
    )
    detail_for_contact_type = models.CharField(
        'Detail for contact type',
        max_length=20,
        default='@example')

    detail = models.ForeignKey(
        to=Contact,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
    )

apps/contacts/forms.py
from django import forms

from apps.contacts.models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('contact_name', 'phone_number')

apps/base/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'index.html'

apps/contacts/views/contact_delete_view.py
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView

from apps.contacts.models import Contact


class ContactDeleteView(DeleteView):
    model = Contact
    success_url = reverse_lazy('contacts:show_all_contacts')

apps/contacts/views/contact_update_view.py
from django.urls import reverse_lazy

from apps.contacts.models import Contact

from django.views.generic.edit import UpdateView


class ContactUpdateView(UpdateView):
    model = Contact
    fields = ['contact_name', 'phone_number']
    template_name_suffix = '_update'
    success_url = reverse_lazy('contacts:show_all_contacts')

apps/contacts/views/contacts_list_view.py
from django.views.generic import ListView

from apps.contacts.models import Contact


class ContactsListView(ListView):
    model = Contact

apps/contacts/views/create_contact_view.py
from django.urls import reverse_lazy

from apps.contacts.models import Contact

from django.views.generic.edit import CreateView


class ContactCreateView(CreateView):
    model = Contact
    fields = ['contact_name', 'phone_number']
    template_name_suffix = '_form'
    success_url = reverse_lazy('contacts:show_all_contacts')

apps/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
            crossorigin="anonymous"></script>
</head>
<body>
{% include '_header.html' %}
<div class="container-fluid">
    {% block body %}
        Welcome
    {% endblock %}
</div>
</body>
</html>

apps/templates/_header.html
<header>
    <div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contacts:show_all_contacts' %}">Phone book</a>
            </li>
        </ul>
    </div>
</header>

apps/templates/contacts/contact_confirm_delete.html
<h2>Delete Contact - {{ object.contact_name }}</h2>

<p>Are you sure you want to delete contact?</p>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm">
</form>

apps/templates/contacts/contact_form.html
{% extends '_base.html' %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create contact</button>
    </form>
{% endblock %}

apps/templates/contacts/contact_list.html
{% extends '_base.html' %}

{% block body %}
    <a href="{% url 'contacts:create_contact' %}">
        <button class="btn btn-primary">Add new contact</button>
    </a>

    <ol>
        {% for contact in object_list %}
            <li style="margin: .2em">
                <span>{{ contact.contact_name }} - {{ contact.phone_number }}</span>
                <a href="{% url 'contacts:edit' pk=contact.pk %}">
                    <button class="btn btn-primary">Edit contact</button>
                </a>
                <a href="{% url 'contacts:delete' pk=contact.pk %}">
                    <button class="btn btn-danger">Delete</button>
                </a>
            </li>
        {% endfor %}
    </ol>
{% endblock %}

apps/templates/contacts/contact_update.html
{% extends '_base.html' %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Update contact</button>
    </form>
{% endblock %}

apps/templates/contacts/edit.html
{% extends '_base.html' %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add contact</button>
    </form>
{% endblock %}

apps/templates/contacts/show_all_contacts.html
{% extends '_base.html' %}

{% block body %}
    <a href="{% url 'contacts:create_contact' %}">
        <button class="btn btn-primary">Add new contact</button>
    </a>

    <ol>
        {% for contact in contacts %}
            <li style="margin: .2em">
                <span>{{ contact.contact_name }} - {{ contact.phone_number }}</span>
                <a href="{% url 'contacts:edit' pk=contact.pk %}">
                    <button class="btn btn-primary">Edit contact</button>
                </a>
                <a href="{% url 'contacts:delete' pk=contact.pk %}">
                    <button class="btn btn-danger">Delete</button>
                </a>
            </li>
        {% endfor %}
    </ol>
{% endblock %}

apps/templates/index.html
{% extends '_base.html' %}

{% block body %}
    <p>Welcome</p>
{% endblock %}